---
type: specs.openrewrite.org/v1beta/recipe
name: io.arconia.rewrite.spring.boot4.MigrateSecurityModule
displayName: Migrate Spring Boot Security module to Spring Boot 4.0
description: Migrate Spring Boot Security module to Spring Boot 4.0.
recipeList:
  - io.arconia.rewrite.spring.boot4.MigrateSecurityTest
  - io.arconia.rewrite.spring.boot4.AddSecurityStarterTest

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.ReactiveUserDetailsServiceAutoConfiguration
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.SecurityProperties
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.SecurityProperties
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.actuate.autoconfigure.security.reactive.EndpointRequest
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.actuate.web.reactive.EndpointRequest
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.actuate.web.reactive.ReactiveManagementWebSecurityAutoConfiguration

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.actuate.web.servlet.EndpointRequest
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.actuate.web.servlet.ManagementWebSecurityAutoConfiguration
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.actuate.autoconfigure.security.servlet.RequestMatcherProvider
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.actuate.web.servlet.SecurityRequestMatchersManagementContextConfiguration
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.actuate.web.servlet.SecurityRequestMatchersManagementContextConfiguration

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.rsocket.RSocketSecurityAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.rsocket.RSocketSecurityAutoConfiguration

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.StaticResourceLocation
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.StaticResourceLocation

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.reactive.PathRequest
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.reactive.PathRequest
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.reactive.ReactiveWebSecurityAutoConfiguration
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.reactive.StaticResourceRequest
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.reactive.StaticResourceRequest

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.ConditionalOnDefaultWebSecurity
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.servlet.ConditionalOnDefaultWebSecurity
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.servlet.PathRequest
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.servlet.PathRequest
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.servlet.SecurityFilterAutoConfiguration
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.servlet.ServletWebSecurityAutoConfiguration
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.autoconfigure.security.servlet.StaticResourceRequest
      newFullyQualifiedTypeName: org.springframework.boot.security.autoconfigure.web.servlet.StaticResourceRequest

  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.security.reactive.ApplicationContextServerWebExchangeMatcher
      newFullyQualifiedTypeName: org.springframework.boot.security.web.reactive.ApplicationContextServerWebExchangeMatcher
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.springframework.boot.security.servlet.ApplicationContextRequestMatcher
      newFullyQualifiedTypeName: org.springframework.boot.security.web.servlet.ApplicationContextRequestMatcher

---
type: specs.openrewrite.org/v1beta/recipe
name: io.arconia.rewrite.spring.boot4.MigrateSecurityTest
displayName: Migrate Security Test
recipeList:
  - org.openrewrite.java.dependencies.ChangeDependency:
      oldGroupId: org.springframework.security
      oldArtifactId: spring-security-test
      newGroupId: org.springframework.boot
      newArtifactId: spring-boot-starter-security-test

---
type: specs.openrewrite.org/v1beta/recipe
name: io.arconia.rewrite.spring.boot4.AddSecurityStarterTest
displayName: Add Security Starter Test
preconditions:
  - org.openrewrite.java.dependencies.FindDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-security
recipeList:
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-security-test
      acceptTransitive: true
      configuration: testImplementation
      scope: test
